server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactivesw
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.common.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: test

app:
  domain:
    name: http://localhost:8088